version: '3.8'

services:
  app:
    image: node:12-alpine
    volumes:
      - ./:/app
    working_dir: /app
    ports:
      - 3000:3000
    command: npm start
    tty: true
  app2:
    image: node:12-alpine
    volumes:
      - ./:/app
    working_dir: /app
    ports:
      - 4000:4000
    command: npm start
    tty: true